Error fixed and restored a property I've addressed an error in the spotifyManager.js file:
TypeError: Cannot read properties of undefined (reading 'length')

The issue has been fixed. I've also restored the source property at Spotify,js. Previously, when the plugin was in use, the resolve method only returned the defaultPlatform instead of both defaultPlatform and source.